### ISSUE TITLE
Exception when using together with Moq 4.18.1

### ISSUE THREAD

**Issue by afilatov-st** [servicetitan/Stl.Fusion#467] opened 2022-06-01 02:12 UTC
I suspect it may be caused by the fact that Moq 4.18.1 uses the new Castle.Core (DynamicProxy) version 5.0.0, while Stl uses 4.4.1 (the issue appears when upgrading Moq 4.16.1 to 4.18.1).

Code causing exception:
```
IServicesCollection Register(IServicesCollection services)
{
        return services
            .UseRegisterAttributeScanner()
            .RegisterFrom(assemblies)
            .Services;
}
```

Stacktrace:
```
System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types.
Could not load type 'Implementation' from assembly 'Stl.Fusion, Version=2.4.59.4351, Culture=neutral, PublicKeyToken=7c239217ec78b545' because the parent type is sealed.
Could not load type 'Implementation' from assembly 'Stl.Fusion, Version=2.4.59.4351, Culture=neutral, PublicKeyToken=7c239217ec78b545' because the parent type is sealed.
  ----> System.TypeLoadException : Could not load type 'Implementation' from assembly 'Stl.Fusion, Version=2.4.59.4351, Culture=neutral, PublicKeyToken=7c239217ec78b545' because the parent type is sealed.
  ----> System.TypeLoadException : Could not load type 'Implementation' from assembly 'Stl.Fusion, Version=2.4.59.4351, Culture=neutral, PublicKeyToken=7c239217ec78b545' because the parent type is sealed.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Stl.Extensibility.MatchingTypeFinder.<>c.<.ctor>b__8_0(Assembly a)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Stl.Extensibility.MatchingTypeFinder..ctor(IEnumerable`1 candidates)
   at Stl.Extensibility.MatchingTypeFinder..ctor(IEnumerable`1 assemblies)
   at Stl.Extensibility.MatchingTypeFinder..ctor()
   at Stl.Fusion.Interception.ArgumentHandlerProvider.Options..ctor()
   at Stl.Fusion.FusionBuilder..ctor(IServiceCollection services)
   at Stl.Fusion.ServiceCollectionExt.AddFusion(IServiceCollection services)
   at Stl.Fusion.RegisterComputeServiceAttribute.Register(IServiceCollection services, Type implementationType)
   at Stl.RegisterAttributes.RegisterAttributeScanner.Register(IEnumerable`1 services, Boolean filterByScope, Boolean filterByType)
   at Stl.RegisterAttributes.RegisterAttributeScanner.RegisterFrom(Assembly[] assemblies)
```

**Comment by alexyakunin** [comment] 2022-06-01 15:05
Yep, we stick to the prev version pf Moq because of this. 

Castle.Core v5 requires some work - they've made a buch of types I used ot inherit generators from private.

**Comment by alexyakunin** [comment] 2022-06-02 05:29
@afilatov-st guys, just curious, do you want to invest a bit & migrate from Castle.Core to Roslyn source generators everywhere? There is an initial (third-party) support for generating Controllers & ClientDefs already, though IMO it makes sense to migrate everything. My guess is that we can do all of this in couple weeks max.

**Comment by alexyakunin** [comment] 2022-06-02 05:33
The main benefits of this are:
- No more need to worry about all the plumbing with controllers & ClientDefs
- Likely, a good performance boost: Castle is boxing every argument, so switching to Tuple-like type for this could let us kill a few allocations per call.

**Comment by afilatov-st** [comment] 2022-06-02 19:48
@alexyakunin can you point to some commits where it was already migrated, just to have an understanding...?

**Comment by wdichler** [comment] 2022-06-14 21:16
I would like help with this issue too.

**Comment by alexyakunin** [comment] 2022-06-20 13:15
@afilatov-st nothing is migrated just yet, I ended up moving the generators to an isolated project for now. Will get back to this later this week (was on a trip, sorry).

**Comment by alexyakunin** [comment] 2022-06-20 13:16
Will share further updates shortly.

**Comment by alexyakunin** [comment] 2022-06-30 01:20
@afilatov-st v3.0.8 is updated to the latest Castle.Core, so this problem should be solved now.

**Comment by alexyakunin** [comment] 2022-07-02 06:58
Confirm the problem is gone, closing the issue.

**Closed by alexyakunin** 2022-07-02 06:58 UTC
Labels: bug
